config/routes.rb
Rails.application.routes.draw do
  resources :artists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artist_path(@artist)
    else
      flash[:notice] = "Name can't be blank"
      render :new
    end
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
    @artist.update(artist_params)

    redirect_to artist_path(@artist)
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    redirect_to artists_path
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/edit.html.erb
<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label "image url" %>
  <%= f.text_area :image %>
  <%= f.submit %>
<% end %>

app/views/artists/index.html.erb
<h1> All Artists </h1>
<%= link_to "New artist", new_artist_path %><br/><br/>

<% @artists.each do |artist| %>
  <%= link_to artist.name, artist_path(artist) %><br/>
<% end %>

app/views/artists/new.html.erb
<%= form_for @artist do |f| %>
  <% if @artist.errors.any? %>
    <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this record form being saved:</h2>
    <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label "image url" %>
  <%= f.text_area :image %>

  <%= f.submit "Save Artist!" %>
<% end %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<%= image_tag @artist.image  %>
<%= link_to "Edit", edit_artist_path %>
<%= link_to "Delete", artist_path(@artist), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MixMaster</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>